// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: apiserver/deletejob/delete_job.proto

package deletejob

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *DeleteJobRequest) Reset() {
	*x = DeleteJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apiserver_deletejob_delete_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobRequest) ProtoMessage() {}

func (x *DeleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_deletejob_delete_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobRequest.ProtoReflect.Descriptor instead.
func (*DeleteJobRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_deletejob_delete_job_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_apiserver_deletejob_delete_job_proto protoreflect.FileDescriptor

var file_apiserver_deletejob_delete_job_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x6a, 0x6f, 0x62, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x6a, 0x6f, 0x62,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x6a, 0x6f,
	0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x32, 0x4f, 0x0a, 0x09, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x12, 0x42, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4a, 0x6f, 0x62, 0x12, 0x1b, 0x2e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x6a, 0x6f, 0x62, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x33, 0x79, 0x6c, 0x68, 0x33, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x6a, 0x6f, 0x62, 0x3b, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x6a, 0x6f, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apiserver_deletejob_delete_job_proto_rawDescOnce sync.Once
	file_apiserver_deletejob_delete_job_proto_rawDescData = file_apiserver_deletejob_delete_job_proto_rawDesc
)

func file_apiserver_deletejob_delete_job_proto_rawDescGZIP() []byte {
	file_apiserver_deletejob_delete_job_proto_rawDescOnce.Do(func() {
		file_apiserver_deletejob_delete_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_apiserver_deletejob_delete_job_proto_rawDescData)
	})
	return file_apiserver_deletejob_delete_job_proto_rawDescData
}

var file_apiserver_deletejob_delete_job_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_apiserver_deletejob_delete_job_proto_goTypes = []interface{}{
	(*DeleteJobRequest)(nil), // 0: deletejob.DeleteJobRequest
	(*emptypb.Empty)(nil),    // 1: google.protobuf.Empty
}
var file_apiserver_deletejob_delete_job_proto_depIdxs = []int32{
	0, // 0: deletejob.DeleteJob.DeleteJob:input_type -> deletejob.DeleteJobRequest
	1, // 1: deletejob.DeleteJob.DeleteJob:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apiserver_deletejob_delete_job_proto_init() }
func file_apiserver_deletejob_delete_job_proto_init() {
	if File_apiserver_deletejob_delete_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apiserver_deletejob_delete_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apiserver_deletejob_delete_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apiserver_deletejob_delete_job_proto_goTypes,
		DependencyIndexes: file_apiserver_deletejob_delete_job_proto_depIdxs,
		MessageInfos:      file_apiserver_deletejob_delete_job_proto_msgTypes,
	}.Build()
	File_apiserver_deletejob_delete_job_proto = out.File
	file_apiserver_deletejob_delete_job_proto_rawDesc = nil
	file_apiserver_deletejob_delete_job_proto_goTypes = nil
	file_apiserver_deletejob_delete_job_proto_depIdxs = nil
}
